version: '3'

services:
  mysql:
    image: mysql:5.7
    networks:
      - production-network
    ports:
      - "1800:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: proposta

  propostas:
    build:
      dockerfile: ./Dockerfile
      context: .
    environment:
      DB_URL: jdbc:mysql://mysql/proposta
      DB_USER: root
      DB_PASSWORD: password

    restart: always
    ports:
      - "8080:8080"
    networks:
      - production-network
    depends_on:
      - mysql


networks:
  production-network:
    driver: bridge
